#!/usr/bin/python
import sqlite3 as sqlite

print "Quiz Generator Database Creator"
DATABASE = raw_input("Type the name of the new DB to init: ")

connection = sqlite.connect(DATABASE)
cursor = connection.cursor()
cursor.execute('CREATE TABLE questions (qid INTEGER PRIMARY KEY, ord INTEGER, q TEXT, ca TEXT, a TEXT, b TEXT, c TEXT, d TEXT, e TEXT, sid INTEGER)')
cursor.execute('CREATE TABLE classes (cid INTEGER PRIMARY KEY, name TEXT, setsReview TEXT, setsNew TEXT)')
cursor.execute('CREATE TABLE sets (sid INTEGER PRIMARY KEY, name TEXT)')
cursor.execute('CREATE TABLE history (hid INTEGER PRIMARY KEY, sid INTEGER, introOrd INTEGER)')
cursor.execute('CREATE TABLE conf (conf TEXT)')
